lualine tweak

diff --git a/install b/install
--- a/install
+++ b/install
@@ -26,3 +26,21 @@ ln -s "$DOTFILES"/alacritty "$HOME"/.config/alacritty
 
 ln -sf "$DOTFILES"/git/gitconfig "$HOME"/.gitconfig
 ln -sf "$DOTFILES"/git/gitignore_global "$HOME"/.gitignore_global
+
+if ! command -v npm &> /dev/null
+then
+    echo "npm executable could not be found"
+else
+    mkdir -p "${HOME}/.local/share/npm-packages"
+    npm config set prefix "${HOME}/.local/share/npm-packages"
+
+    npm i -g tree-sitter-cli
+fi
+
+if ! command -v git &> /dev/null
+then
+    echo "git executable could not be found"
+else
+    mkdir -p "${HOME}/.local/share/nvim/opt"
+    git clone git@github.com:phpactor/phpactor "${HOME}/.local/share/nvim/opt/phpactor"
+fi
